version: "3.9"
name: forumsaglik-dev

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forumsaglik_dev
      TZ: Europe/Istanbul
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d forumsaglik_dev"]
      interval: 3s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 30

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8025:8025" # UI http://localhost:8025
  #     - "1025:1025" # SMTP

volumes:
  pgdata_dev: {}
  redisdata_dev: {}
