version: "3.9"
name: forum-stack

services:
  traefik:
    image: traefik:v3.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=${TZ}
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=forum-stack_web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=true
      - --accesslog=true
      - --accesslog.fields.headers.defaultmode=keep
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/letsencrypt:/letsencrypt
      - ./data/traefik/.htpasswd:/etc/traefik/.htpasswd:ro

    labels:
      - traefik.enable=true

      # 1) www & app -> apex redirect (301)
      - traefik.http.middlewares.to-apex.redirectregex.regex=^https?://(www\.|app\.)?forumsaglik\.com/?(.*)$
      - traefik.http.middlewares.to-apex.redirectregex.replacement=https://forumsaglik.com/$$2
      - traefik.http.middlewares.to-apex.redirectregex.permanent=true

      # 2) www router (sadece redirect uygular)
      - traefik.http.routers.www.rule=Host(`www.forumsaglik.com`)
      - traefik.http.routers.www.entrypoints=websecure
      - traefik.http.routers.www.tls.certresolver=le
      - traefik.http.routers.www.middlewares=to-apex
      - traefik.http.routers.www.service=noop@internal

      # 3) Dashboard router (yalnızca /dashboard ve /api yollarını aç)
      - traefik.http.routers.traefik.rule=Host(`traefik.forumsaglik.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-auth,traefik-sec-headers,traefik-ratelimit
      # 3.a) Basic Auth middleware (usersFile ile)
      - traefik.http.middlewares.traefik-auth.basicauth.usersfile=/etc/traefik/.htpasswd
      # 3.b) Basit güvenlik header’ları
      - traefik.http.middlewares.traefik-sec-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.traefik-sec-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.traefik-sec-headers.headers.stsPreload=true
      - traefik.http.middlewares.traefik-sec-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.traefik-sec-headers.headers.browserXssFilter=true
      - traefik.http.middlewares.traefik-sec-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.traefik-sec-headers.headers.customResponseHeaders.X-Robots-Tag=noindex, nofollow
      # 3.c) Brute force'a karşı temel rate limit
      - traefik.http.middlewares.traefik-ratelimit.ratelimit.average=50
      - traefik.http.middlewares.traefik-ratelimit.ratelimit.burst=100
    networks: [web]

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [internal]

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [internal]

  backend:
    image: ghcr.io/edcaglar/forumsaglik-backend:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - ./.env
    environment:
      # docker içi host/portlar
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${API_HOST}`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.services.api.loadbalancer.server.port=${UVICORN_PORT}
      - traefik.docker.network=forum-stack_web
    networks: [web, internal]

  frontend:
    image: ghcr.io/edcaglar/forumsaglik-frontend:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - ./.env
    environment:
      INTERNAL_API_URL: ${INTERNAL_API_URL} # SSR tarafı backend'e iç ağdan gider
    depends_on: [backend]
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=3000
      - traefik.docker.network=forum-stack_web
    networks: [web, internal]

  pgadmin:
    image: dpage/pgadmin4:8.12
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "40"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks: [web, internal]
    labels:
      - traefik.enable=true
      # Router
      - traefik.http.routers.pgadmin.rule=Host(`dbadmin.forumsaglik.com`)
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.tls.certresolver=le
      # pgAdmin konteyner içi port
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      # Traefik hangi ağı kullanacak?
      - traefik.docker.network=forum-stack_web
      # rate limit
      - traefik.http.middlewares.pgadmin-rl.ratelimit.average=30
      - traefik.http.middlewares.pgadmin-rl.ratelimit.burst=60
      # Güvenlik header'ları (light)
      - traefik.http.middlewares.pgadmin-sec.headers.stsSeconds=31536000
      - traefik.http.middlewares.pgadmin-sec.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.pgadmin-sec.headers.stsPreload=true
      - traefik.http.middlewares.pgadmin-sec.headers.contentTypeNosniff=true
      - traefik.http.middlewares.pgadmin-sec.headers.browserXssFilter=true
      - traefik.http.middlewares.pgadmin-sec.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.pgadmin-sec.headers.customResponseHeaders.X-Robots-Tag=noindex, nofollow

      # Zinciri router'a bağla
      - traefik.http.routers.pgadmin.middlewares=pgadmin-rl,pgadmin-sec,traefik-auth@docker

networks:
  web: {}
  internal:
    internal: true

volumes:
  pgdata: {}
  redisdata: {}
