name: prod-deploy

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker-compose.yml"
      - "deploy.sh"
      - ".github/workflows/**"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/forumsaglik-backend
  FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/forumsaglik-frontend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Backend imajı
      - name: Build & Push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Frontend imajı (Next public env build-time!)
      - name: Build & Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL || 'https://api.forumsaglik.com' }}
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      # Repo'yu checkout et (deploy.sh ve docker-compose.yml için)
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Show workspace tree for debug
        run: |
          pwd
          ls -la
          echo "----"
          git status --porcelain
      # 1) docker-compose.yml ve deploy.sh dosyalarını EC2'ye kopyala
      - name: Upload compose & deploy script to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,deploy.sh"
          target: /opt/forum-stack
      # 2) EC2'de deploy.sh çalıştır (yeni imajları çek ve container'ları yeniden başlat)
      - name: SSH to EC2 & deploy (pin by SHA)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /opt/forum-stack
            IMAGE_TAG=${{ github.sha }} ./deploy.sh
